#!/bin/bash


# Try using the -z test:

# if [ -z "$1" ] && [ -z "$2" ]
# From man bash:

# -z string
#    True if the length of string is zero.


# unmount $1

if [ -z "$1" ]; 
  then echo "Enter a disk. (i.e. /dev/sda )"; 
  else
    sudo umount $1; 
    sudo hdparm -S 1 $1;
fi